import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import * as schema from "./schema";
import { nanoid } from "nanoid";
import path from "path";

const dbPath = path.join(process.cwd(), "roundup.db");
const sqlite = new Database(dbPath);
sqlite.pragma("journal_mode = WAL");
sqlite.pragma("foreign_keys = ON");
const db = drizzle(sqlite, { schema });

migrate(db, { migrationsFolder: path.join(process.cwd(), "drizzle") });

function J(v: unknown) { return JSON.stringify(v); }

const charityData = [
  // === EXISTING 6 (updated with new fields) ===
  {
    id: nanoid(), name: "Médecins Sans Frontières", description: "Independent medical humanitarian assistance wherever people are threatened by conflict, epidemics, or disasters.",
    category: "humanitarian", icon: "🏥", qualityLabel: "Don en Confiance", taxRate: 75, currency: "EUR",
    mission: "Founded in 1971 by French doctors who witnessed the Biafra crisis, MSF broke the silence on humanitarian emergencies and pioneered témoignage: bearing witness. Today MSF operates in over 70 countries with 67,000+ staff.\n\nMSF received the Nobel Peace Prize in 1999 for its pioneering humanitarian work. The organisation remains fiercely independent, refusing government funding that could compromise its neutrality.",
    impact: J(["Treated 11.2 million outpatient cases across 74 countries in 2024","Performed 118,400 surgical procedures","Vaccinated 3.4 million people","Provided mental health support to 437,000 individuals","Delivered 385,000 babies in MSF facilities"]),
    crisisEligible: true,
    foundingStory: "In 1968, French doctors volunteered in Biafra during the Nigerian civil war. They witnessed starvation and massacres but were bound by Red Cross neutrality rules. In 1971, they founded MSF with a radical idea: medical teams should go wherever needed, and never be silent about what they see.",
    howMoneyHelps: J([{amount:1,description:"Provides 10 doses of oral rehydration salts"},{amount:7,description:"Funds one day of treatment for a malnourished child"},{amount:30,description:"Supplies a complete emergency surgery kit"}]),
    milestones: J([{year:1971,title:"MSF Founded",description:"French doctors refuse to stay silent"},{year:1999,title:"Nobel Peace Prize",description:"Recognised for pioneering humanitarian medical work"},{year:2014,title:"Ebola Response",description:"Largest ever MSF operation"},{year:2024,title:"11.2M Patients",description:"Record year of outpatient consultations"}]),
    financialBreakdown: J({programs:89,admin:6,fundraising:5}), fundraisingEfficiency: "89 cents of every euro goes directly to saving lives",
    countryOfOrigin: "FR", foundedYear: 1971, websiteUrl: "https://www.msf.org",
    certifications: J([{name:"Don en Confiance",year:1989},{name:"Nobel Peace Prize",year:1999}]),
    jurisdictionsEligible: J(["FR","GB","DE","BE","ES"]), loiColucheEligible: true, crossBorderMethod: "national_entity",
  },
  {
    id: nanoid(), name: "WWF France", description: "Protecting biodiversity, restoring ecosystems, and building a future where people and nature thrive.",
    category: "environment", icon: "🐼", qualityLabel: "Don en Confiance", taxRate: 66, currency: "EUR",
    mission: "Founded in 1961, WWF is the world's largest conservation organisation, working in over 100 countries. WWF France focuses on French biodiversity: restoring river ecosystems, creating marine reserves, building wildlife corridors.\n\nThe panda logo represents WWF's mission to halt the destruction of the natural environment.",
    impact: J(["Protected 1.2 million hectares of marine habitat","Restored 340 km of river ecosystems","Planted 500,000 trees","Campaigned for 30% marine protection by 2030","Published the Living Planet Report"]),
    crisisEligible: false,
    foundingStory: "In 1961, scientists and conservationists saw wildlife disappearing at alarming rates. They created the World Wildlife Fund. The panda logo was inspired by Chi Chi, a giant panda at London Zoo.",
    howMoneyHelps: J([{amount:5,description:"Protects 1 hectare of forest for a month"},{amount:15,description:"Funds one day of anti-poaching patrol"},{amount:50,description:"Supports rescue of an injured sea turtle"}]),
    milestones: J([{year:1961,title:"WWF Founded",description:"Created for global wildlife conservation"},{year:1986,title:"Panda Logo Global",description:"Most recognised conservation symbol"},{year:2010,title:"Earth Hour",description:"128 countries participate"},{year:2024,title:"Marine Milestone",description:"1.2M hectares protected"}]),
    financialBreakdown: J({programs:82,admin:10,fundraising:8}), fundraisingEfficiency: "82 cents of every euro funds conservation",
    countryOfOrigin: "CH", foundedYear: 1961, websiteUrl: "https://www.wwf.fr",
    certifications: J([{name:"Don en Confiance",year:2005}]),
    jurisdictionsEligible: J(["FR","GB","DE","BE","ES"]), loiColucheEligible: false, crossBorderMethod: "national_entity",
  },
  {
    id: nanoid(), name: "Ligue contre le cancer", description: "France's leading independent cancer charity since 1918.",
    category: "health", icon: "🎗️", qualityLabel: "Don en Confiance", taxRate: 66, currency: "EUR",
    mission: "The Ligue contre le cancer is a federation of 103 departmental committees, entirely independent of pharmaceutical companies.\n\nThe Ligue funds over 500 research projects annually, supports patients and families, and leads national prevention campaigns.",
    impact: J(["Funded 532 research projects in 2024","Supported 680,000 patients and families","Trained 12,000 volunteers","Led tobacco control advocacy","Cancer Info helpline: 45,000 calls per year"]),
    crisisEligible: false,
    foundingStory: "In 1918, Justin Godart saw cancer silently killing as many French people as the war itself. He founded the Ligue to fight a disease no one talked about.",
    howMoneyHelps: J([{amount:10,description:"Funds one hour of laboratory research"},{amount:25,description:"Provides a psychological support session"},{amount:100,description:"Funds a cancer screening campaign"}]),
    milestones: J([{year:1918,title:"Ligue Founded",description:"Justin Godart creates France's first cancer charity"},{year:2000,title:"Tobacco Victory",description:"Landmark tobacco control legislation"},{year:2024,title:"532 Research Grants",description:"Largest ever annual commitment"}]),
    financialBreakdown: J({programs:78,admin:12,fundraising:10}), fundraisingEfficiency: "78 cents of every euro funds research and patient support",
    countryOfOrigin: "FR", foundedYear: 1918, websiteUrl: "https://www.ligue-cancer.net",
    certifications: J([{name:"Don en Confiance",year:1990}]),
    jurisdictionsEligible: J(["FR"]), loiColucheEligible: false, crossBorderMethod: "none",
  },
  {
    id: nanoid(), name: "Restos du Cœur", description: "Founded by Coluche in 1985. The charity behind the Loi Coluche tax law.",
    category: "humanitarian", icon: "❤️", qualityLabel: "Don en Confiance", taxRate: 75, currency: "EUR",
    mission: "Les Restos du Cœur were born from a comedian's outrage. In 1985, Coluche went on the radio: \"I have a little idea. If there are people who are ready to give food...\" Within weeks, thousands responded.\n\nToday, Restos distributes over 140 million meals per year through 2,100 centres staffed by 73,000 volunteers. The Loi Coluche was literally named in honour of their founder.",
    impact: J(["Distributed 142 million meals in 2024","Helped 1.2 million people through winter","Operated 2,100 centres","43,000 people received housing support","73,000 volunteers donated their time"]),
    crisisEligible: true,
    foundingStory: "On 26 September 1985, comedian Coluche launched a radio appeal. The response was overwhelming. He died in 1986, but his Restos became permanent. The Loi Coluche, passed in 1988, enshrined his belief that generosity should be rewarded.",
    howMoneyHelps: J([{amount:1,description:"Provides 4 balanced meals"},{amount:10,description:"Feeds a family for a full week"},{amount:50,description:"Provides a complete winter clothing kit"}]),
    milestones: J([{year:1985,title:"Coluche Founds Restos",description:"A comedian's radio appeal creates France's largest food charity"},{year:1988,title:"Loi Coluche Passed",description:"75% tax deduction law named after founder"},{year:2020,title:"COVID Response",description:"Meal distribution doubles"},{year:2024,title:"142M Meals",description:"Record year"}]),
    financialBreakdown: J({programs:92,admin:5,fundraising:3}), fundraisingEfficiency: "92 cents of every euro goes directly to people in need",
    countryOfOrigin: "FR", foundedYear: 1985, websiteUrl: "https://www.restosducoeur.org",
    certifications: J([{name:"Don en Confiance",year:1992}]),
    jurisdictionsEligible: J(["FR"]), loiColucheEligible: true, crossBorderMethod: "none",
  },
  {
    id: nanoid(), name: "Amnesty International", description: "Defending human rights worldwide through investigation, advocacy, and campaigns since 1961.",
    category: "human_rights", icon: "✊", qualityLabel: null, taxRate: 66, currency: "EUR",
    mission: "Amnesty began in 1961 when British lawyer Peter Benenson read about students imprisoned for raising a toast to freedom. Today, Amnesty has over 10 million supporters in 150+ countries.\n\nFunded entirely by individual donations, refusing government money to maintain independence.",
    impact: J(["Secured release of 98 prisoners of conscience in 2024","Published 340 investigative reports","Mobilised 10.7 million supporters","Campaigned for arms trade treaties","350,000 French supporters in campaigns"]),
    crisisEligible: false,
    foundingStory: "On 28 May 1961, Peter Benenson published 'The Forgotten Prisoners' in The Observer. Within weeks, thousands in dozens of countries wrote letters demanding students' release. Amnesty was born from the belief that ordinary letters can hold governments accountable.",
    howMoneyHelps: J([{amount:5,description:"Translates an urgent appeal into 3 languages"},{amount:20,description:"Funds a legal observation mission"},{amount:100,description:"Supports a human rights investigation team for one day"}]),
    milestones: J([{year:1961,title:"Amnesty Founded",description:"Peter Benenson's newspaper appeal"},{year:1977,title:"Nobel Peace Prize",description:"Recognised for human rights work"},{year:2024,title:"157 Countries",description:"Most comprehensive year of documentation"}]),
    financialBreakdown: J({programs:75,admin:14,fundraising:11}), fundraisingEfficiency: "75 cents of every euro funds investigations and campaigns",
    countryOfOrigin: "GB", foundedYear: 1961, websiteUrl: "https://www.amnesty.org",
    certifications: J([{name:"Nobel Peace Prize",year:1977}]),
    jurisdictionsEligible: J(["FR","GB","DE","BE","ES"]), loiColucheEligible: false, crossBorderMethod: "national_entity",
  },
  {
    id: nanoid(), name: "Secours Populaire", description: "Fighting poverty in France since 1945 through food, housing, and holidays for children who have never seen the sea.",
    category: "humanitarian", icon: "🤝", qualityLabel: "Don en Confiance", taxRate: 75, currency: "EUR",
    mission: "Founded in 1945 from the solidarity of the Resistance. With 80,000 volunteers, Secours Populaire reaches 3.5 million people annually.\n\nWhat makes them unique: dignity matters as much as survival. Beyond food and housing, they provide access to culture, sport, and holidays. Their 'Journées des Oubliés des Vacances' takes children on their first trip to the seaside.",
    impact: J(["Assisted 3.5 million people in 2024","Holidays for 65,000 children","Emergency aid in 48 countries","1,300 distribution centres","80,000 volunteers"]),
    crisisEligible: true,
    foundingStory: "In 1945, as France emerged from occupation, Secours Populaire was created by the Resistance. Their founding principle: everyone deserves not just survival but dignity.",
    howMoneyHelps: J([{amount:2,description:"Provides school supplies for one child"},{amount:15,description:"Funds a day at the seaside for a child"},{amount:40,description:"Provides a complete back-to-school kit"}]),
    milestones: J([{year:1945,title:"Founded Post-Liberation",description:"Born from Resistance solidarity"},{year:1985,title:"First Journée des Oubliés",description:"First seaside trip for disadvantaged children"},{year:2024,title:"3.5M People Helped",description:"Record year as cost of living crisis deepens"}]),
    financialBreakdown: J({programs:88,admin:7,fundraising:5}), fundraisingEfficiency: "88 cents of every euro funds food, housing, and holidays",
    countryOfOrigin: "FR", foundedYear: 1945, websiteUrl: "https://www.secourspopulaire.fr",
    certifications: J([{name:"Don en Confiance",year:1995}]),
    jurisdictionsEligible: J(["FR"]), loiColucheEligible: true, crossBorderMethod: "none",
  },

  // === 17 NEW CHARITIES ===
  // European (5)
  {
    id: nanoid(), name: "Deutsche Krebshilfe", description: "Germany's largest independent cancer research charity, funding science without pharmaceutical industry ties since 1974.",
    category: "health", icon: "🔬", qualityLabel: "DZI Spendensiegel", taxRate: 42, currency: "EUR",
    mission: "Founded by physician Mildred Scheel in 1974, Deutsche Krebshilfe is the Federal Republic's most important private funder of cancer research. Like France's Ligue contre le cancer, it accepts zero pharma money.\n\nIt funds clinical trials, supports patient information centres, and runs nationwide cancer prevention campaigns.",
    impact: J(["Funded 3,200+ research projects since founding","€250 million invested in research in 2024","Supports 8 comprehensive cancer centres across Germany","Runs the national INFONETZ KREBS helpline","Prevention campaigns reaching 12 million schoolchildren"]),
    crisisEligible: false,
    foundingStory: "In 1974, Mildred Scheel, a physician and wife of West German President Walter Scheel, saw that cancer research in Germany was chronically underfunded. She founded Deutsche Krebshilfe to raise private money free from any industry influence. Her vision: every cancer patient deserves the best science, regardless of what is profitable.",
    howMoneyHelps: J([{amount:10,description:"Funds one hour of laboratory cancer research"},{amount:50,description:"Supports a clinical trial participant for a day"},{amount:200,description:"Equips a research lab for a week"}]),
    milestones: J([{year:1974,title:"Founded",description:"Mildred Scheel launches Germany's cancer charity"},{year:1990,title:"East-West Expansion",description:"Extends research funding to reunified Germany"},{year:2010,title:"National Cancer Plan",description:"Instrumental in creating Germany's national strategy"},{year:2024,title:"€250M Research",description:"Record annual investment"}]),
    financialBreakdown: J({programs:91,admin:5,fundraising:4}), fundraisingEfficiency: "91 cents of every euro funds cancer research and patient support",
    countryOfOrigin: "DE", foundedYear: 1974, websiteUrl: "https://www.krebshilfe.de",
    certifications: J([{name:"DZI Spendensiegel",year:1992}]),
    jurisdictionsEligible: J(["DE","FR"]), loiColucheEligible: false, crossBorderMethod: "tge",
  },
  {
    id: nanoid(), name: "SOS Children's Villages", description: "Providing loving homes and family-based care for children who have lost parental care in 138 countries.",
    category: "children", icon: "🏡", qualityLabel: "DZI Spendensiegel", taxRate: 66, currency: "EUR",
    mission: "Founded in 1949 by Hermann Gmeiner in post-war Austria, SOS Children's Villages pioneered the idea that every child deserves a family. When no family is available, SOS creates one.\n\nToday, SOS operates in 138 countries, caring for over 80,000 children in family-style homes, running schools, medical centres, and youth programmes.",
    impact: J(["80,000+ children in direct SOS family care worldwide","2.5 million children and adults reached through community programmes","1,500 SOS facilities in 138 countries","99% of SOS children complete secondary education","75 years of unbroken family-based care"]),
    crisisEligible: true,
    foundingStory: "In 1949, Hermann Gmeiner, a young medical student in Innsbruck, saw thousands of orphans in post-war Austria. Orphanages were cold, institutional places. He had a different idea: give every child a mother, siblings, a house, and a village. He built the first SOS Children's Village in Imst, Austria, funded by donations he collected door to door.",
    howMoneyHelps: J([{amount:5,description:"Provides a day of care, food, and education for one child"},{amount:30,description:"School supplies for a child for an entire year"},{amount:100,description:"Supports a family unit for a full month"}]),
    milestones: J([{year:1949,title:"First Village Built",description:"Hermann Gmeiner builds the first SOS village in Imst, Austria"},{year:1960,title:"Global Expansion",description:"SOS reaches Africa, Asia, and Latin America"},{year:2003,title:"UN Consultative Status",description:"Recognised as leading voice for children without parental care"},{year:2024,title:"138 Countries",description:"Largest non-governmental childcare organisation"}]),
    financialBreakdown: J({programs:83,admin:9,fundraising:8}), fundraisingEfficiency: "83 cents of every euro directly supports children and families",
    countryOfOrigin: "AT", foundedYear: 1949, websiteUrl: "https://www.sos-childrensvillages.org",
    certifications: J([{name:"DZI Spendensiegel",year:1980}]),
    jurisdictionsEligible: J(["FR","DE","BE","ES"]), loiColucheEligible: false, crossBorderMethod: "national_entity",
  },
  {
    id: nanoid(), name: "Terre des Hommes", description: "Protecting children's rights: ending exploitation, ensuring education, and providing justice in 30+ countries.",
    category: "children", icon: "👶", qualityLabel: "ZEWO", taxRate: 66, currency: "EUR",
    mission: "Founded in 1960 by Edmond Kaiser in Lausanne, Terre des Hommes began by evacuating children from war zones. Today it focuses on systemic change: ending child labour, combating trafficking, ensuring access to education and justice.\n\nTerre des Hommes works in over 30 countries, focusing on the root causes of why children suffer rather than just the symptoms.",
    impact: J(["Protected 4.2 million children worldwide in 2024","Rescued 12,000 children from exploitation","Provided legal aid to 8,500 migrant children","Enrolled 150,000 children in education programmes","Active in 34 countries across 4 continents"]),
    crisisEligible: false,
    foundingStory: "In 1960, Edmond Kaiser read about children dying in the Algerian War. He decided to act, founding Terre des Hommes ('Earth of Humanity') in Lausanne. The name came from Antoine de Saint-Exupéry's book. Kaiser's first act: evacuating wounded children from Algeria to Swiss hospitals.",
    howMoneyHelps: J([{amount:3,description:"Protects one child from exploitation for a day"},{amount:20,description:"Provides legal aid for a migrant child"},{amount:75,description:"Enrolls a child in school for a year"}]),
    milestones: J([{year:1960,title:"Founded in Lausanne",description:"Edmond Kaiser evacuates children from war"},{year:1989,title:"UN Convention",description:"Instrumental in drafting the UN Convention on the Rights of the Child"},{year:2010,title:"Anti-Trafficking Campaign",description:"Launches major campaign against child trafficking"},{year:2024,title:"4.2M Children Protected",description:"Largest reach in organisation's history"}]),
    financialBreakdown: J({programs:85,admin:8,fundraising:7}), fundraisingEfficiency: "85 cents of every euro directly protects children",
    countryOfOrigin: "CH", foundedYear: 1960, websiteUrl: "https://www.terredeshommes.org",
    certifications: J([{name:"ZEWO",year:1975}]),
    jurisdictionsEligible: J(["FR","DE","BE","ES"]), loiColucheEligible: false, crossBorderMethod: "tge",
  },
  {
    id: nanoid(), name: "Greenpeace", description: "Independent environmental campaigns against climate change, deforestation, and ocean destruction. Zero corporate funding.",
    category: "environment", icon: "🌍", qualityLabel: null, taxRate: 66, currency: "EUR",
    mission: "Founded in 1971 when a small group sailed to Amchitka Island to protest nuclear testing. Today Greenpeace operates in 55 countries with 3 million supporters.\n\nGreenpeace refuses all corporate and government money. Every campaign, every ship, every action is funded entirely by individual donors. This independence is non-negotiable.",
    impact: J(["Campaigns led to bans on commercial whaling, Arctic oil drilling, and deep-sea mining","3 million individual supporters in 55 countries","Rainbow Warrior fleet monitors illegal fishing globally","Successful pressure on 100+ companies to eliminate deforestation from supply chains","Led campaign resulting in Global Plastics Treaty negotiations"]),
    crisisEligible: false,
    foundingStory: "In 1971, a small crew sailed from Vancouver toward Amchitka Island, Alaska, to protest US nuclear weapons testing. Their boat was called the Phyllis Cormack, but they gave themselves a bigger name: Greenpeace. The test went ahead, but the public outcry they generated forced the US to cancel future tests. Direct action was born.",
    howMoneyHelps: J([{amount:5,description:"Funds one day of ocean patrol monitoring illegal fishing"},{amount:25,description:"Pays for laboratory water sample analysis"},{amount:100,description:"Supports one day of a campaign action"}]),
    milestones: J([{year:1971,title:"Founded",description:"Crew sails to protest nuclear testing"},{year:1985,title:"Rainbow Warrior",description:"French agents sink the Greenpeace flagship, galvanising global support"},{year:2018,title:"Plastics Campaign",description:"Launches global campaign against single-use plastics"},{year:2024,title:"55 Countries",description:"Largest independent environmental network"}]),
    financialBreakdown: J({programs:80,admin:8,fundraising:12}), fundraisingEfficiency: "80 cents of every euro funds environmental campaigns",
    countryOfOrigin: "NL", foundedYear: 1971, websiteUrl: "https://www.greenpeace.org",
    certifications: J([]),
    jurisdictionsEligible: J(["FR","GB","DE","BE","ES"]), loiColucheEligible: false, crossBorderMethod: "national_entity",
  },
  {
    id: nanoid(), name: "Handicap International", description: "Supporting people with disabilities and protecting civilians from explosive weapons. Nobel Peace Prize co-laureate.",
    category: "disability", icon: "♿", qualityLabel: "IDEAS", taxRate: 75, currency: "EUR",
    mission: "Founded in 1982 in Lyon by two French doctors who saw amputees abandoned without care in Cambodian refugee camps. Handicap International (now Humanity & Inclusion) operates in 60 countries.\n\nThe organisation provides prosthetics, rehabilitation, and inclusion programmes while campaigning to ban landmines and cluster munitions. Their advocacy co-led to the 1997 Mine Ban Treaty, for which they shared the Nobel Peace Prize.",
    impact: J(["Supported 3.5 million people with disabilities in 2024","Provided 28,000 prosthetics and mobility devices","Cleared landmines from 400+ square km","Co-laureate of the Nobel Peace Prize for the Mine Ban Treaty","Active in 60 countries with focus on conflict zones"]),
    crisisEligible: true,
    foundingStory: "In 1982, doctors Jean-Baptiste Richardier and Yves Gaumeton were working in Thai refugee camps. They saw hundreds of Cambodian amputees, victims of landmines, receiving no rehabilitation. They returned to Lyon and founded Handicap International to send prosthetics, physiotherapists, and hope to people the world had forgotten.",
    howMoneyHelps: J([{amount:10,description:"Provides a pair of crutches for mobility"},{amount:40,description:"Funds a prosthetic component for a limb"},{amount:150,description:"Full rehabilitation for a landmine survivor"}]),
    milestones: J([{year:1982,title:"Founded in Lyon",description:"Two doctors respond to Cambodian amputee crisis"},{year:1992,title:"Ban Landmines Campaign",description:"Co-founds International Campaign to Ban Landmines"},{year:1997,title:"Nobel Peace Prize",description:"Shared prize for Mine Ban Treaty advocacy"},{year:2024,title:"3.5M Supported",description:"Record reach across 60 countries"}]),
    financialBreakdown: J({programs:86,admin:7,fundraising:7}), fundraisingEfficiency: "86 cents of every euro funds disability support and mine clearance",
    countryOfOrigin: "FR", foundedYear: 1982, websiteUrl: "https://www.hi.org",
    certifications: J([{name:"IDEAS",year:2012},{name:"Nobel Peace Prize",year:1997}]),
    jurisdictionsEligible: J(["FR","GB","DE","BE","ES"]), loiColucheEligible: true, crossBorderMethod: "national_entity",
  },
  // International (3)
  {
    id: nanoid(), name: "UNICEF", description: "The United Nations Children's Fund: vaccinations, nutrition, education, and emergency aid for children in 190+ countries.",
    category: "children", icon: "🧒", qualityLabel: null, taxRate: 75, currency: "EUR",
    mission: "Created in 1946 to feed starving children in post-war Europe, UNICEF has evolved into the world's leading children's organisation. Present in 190+ countries, it delivers vaccines, therapeutic food, clean water, and education.\n\nUNICEF received the Nobel Peace Prize in 1965. It remains the only UN agency funded entirely by voluntary contributions.",
    impact: J(["Vaccinated 49% of the world's children under 5","Provided therapeutic food for 6.7 million malnourished children","Supplied clean water to 48 million people","Reached 72 million children with education programmes","First responder in every major humanitarian crisis"]),
    crisisEligible: true,
    foundingStory: "In December 1946, the United Nations General Assembly created UNICEF to provide emergency food and healthcare to children in post-war Europe. What began as a temporary fund became permanent when the world realised that children's needs never end.",
    howMoneyHelps: J([{amount:1,description:"Provides 5 doses of life-saving vaccine"},{amount:10,description:"School supplies for one child for a year"},{amount:50,description:"Therapeutic food for 35 severely malnourished children"}]),
    milestones: J([{year:1946,title:"UNICEF Created",description:"UN establishes children's emergency fund"},{year:1965,title:"Nobel Peace Prize",description:"Recognised for children's advocacy worldwide"},{year:2000,title:"Millennium Goals",description:"Key architect of child-focused development goals"},{year:2024,title:"190+ Countries",description:"Universal presence for children"}]),
    financialBreakdown: J({programs:87,admin:6,fundraising:7}), fundraisingEfficiency: "87 cents of every euro reaches children directly",
    countryOfOrigin: "US", foundedYear: 1946, websiteUrl: "https://www.unicef.org",
    certifications: J([{name:"Nobel Peace Prize",year:1965}]),
    jurisdictionsEligible: J(["FR","GB","DE","BE","ES"]), loiColucheEligible: true, crossBorderMethod: "national_entity",
  },
  {
    id: nanoid(), name: "Red Cross / ICRC", description: "Humanitarian protection and assistance for victims of armed conflict. Founded 1863. Three Nobel Peace Prizes.",
    category: "humanitarian", icon: "🏥", qualityLabel: null, taxRate: 75, currency: "EUR",
    mission: "The International Committee of the Red Cross was founded in 1863 by Henry Dunant after witnessing the Battle of Solferino. ICRC is the guardian of the Geneva Conventions and operates in the world's most dangerous conflict zones.\n\nWith three Nobel Peace Prizes (1917, 1944, 1963), the Red Cross is the oldest and most recognised humanitarian organisation in the world.",
    impact: J(["Visited 850,000 detainees in 90+ countries","Reunited 5,200 families separated by conflict","Provided clean water to 30 million people","Trained 12 million people in first aid","Responded to every major armed conflict"]),
    crisisEligible: true,
    foundingStory: "On 24 June 1859, Swiss businessman Henry Dunant arrived in Solferino, Italy, during a battle between French and Austrian armies. He found 40,000 wounded soldiers abandoned on the battlefield. Dunant organised local villagers to help, then returned to Geneva and wrote 'A Memory of Solferino', proposing an international organisation to care for war wounded. The Red Cross was born.",
    howMoneyHelps: J([{amount:5,description:"Provides an emergency shelter blanket for a displaced family"},{amount:20,description:"A week of clean water for a family in a conflict zone"},{amount:100,description:"A complete emergency medical kit"}]),
    milestones: J([{year:1863,title:"ICRC Founded",description:"Henry Dunant's vision after the Battle of Solferino"},{year:1864,title:"First Geneva Convention",description:"Rules of war codified for the first time"},{year:1917,title:"First Nobel Prize",description:"Recognised during World War I"},{year:2024,title:"Global Presence",description:"Active in 100+ conflict-affected countries"}]),
    financialBreakdown: J({programs:90,admin:6,fundraising:4}), fundraisingEfficiency: "90 cents of every euro reaches conflict-affected communities",
    countryOfOrigin: "CH", foundedYear: 1863, websiteUrl: "https://www.icrc.org",
    certifications: J([{name:"Nobel Peace Prize",year:1917},{name:"Nobel Peace Prize",year:1944},{name:"Nobel Peace Prize",year:1963}]),
    jurisdictionsEligible: J(["FR","GB","DE","BE","ES"]), loiColucheEligible: true, crossBorderMethod: "national_entity",
  },
  {
    id: nanoid(), name: "Save the Children", description: "Every child deserves a future: education, protection, and healthcare in 120+ countries since 1919.",
    category: "children", icon: "📚", qualityLabel: "Charity Commission", taxRate: 66, currency: "GBP",
    mission: "Founded in 1919 by Eglantyne Jebb, who declared: 'Every war is a war against children.' Save the Children was the first organisation to draft a declaration of children's rights, which became the UN Convention on the Rights of the Child.\n\nToday, Save the Children works in 120+ countries, responding to emergencies, running education programmes, and fighting child poverty.",
    impact: J(["Reached 40 million children in 2024","Responded to 94 humanitarian emergencies","Provided education to 9.2 million children","Reduced child mortality in 30 programme countries","120+ countries of operation"]),
    crisisEligible: true,
    foundingStory: "In 1919, Eglantyne Jebb was arrested for distributing leaflets showing starving Austrian children. The case was dismissed, and the judge donated to her cause. She founded Save the Children to help all children, including those of former enemies. She went on to draft the first Declaration of the Rights of the Child.",
    howMoneyHelps: J([{amount:3,description:"A textbook for a child in a crisis zone"},{amount:15,description:"Emergency nutrition for a child for a week"},{amount:50,description:"Protects a child from trafficking for a month"}]),
    milestones: J([{year:1919,title:"Founded by Eglantyne Jebb",description:"Helps children of former enemies"},{year:1924,title:"Rights of the Child",description:"Jebb's declaration adopted by League of Nations"},{year:1989,title:"UN Convention",description:"Jebb's declaration becomes binding international law"},{year:2024,title:"40M Children Reached",description:"Largest year of impact"}]),
    financialBreakdown: J({programs:84,admin:8,fundraising:8}), fundraisingEfficiency: "84 pence of every pound directly helps children",
    countryOfOrigin: "GB", foundedYear: 1919, websiteUrl: "https://www.savethechildren.org.uk",
    certifications: J([{name:"Charity Commission",year:1919}]),
    jurisdictionsEligible: J(["GB","FR","DE","BE","ES"]), loiColucheEligible: false, crossBorderMethod: "national_entity",
  },
  // UK (3)
  {
    id: nanoid(), name: "Cancer Research UK", description: "The world's largest independent cancer research charity, pioneering life-saving treatments since 2002.",
    category: "health", icon: "🔬", qualityLabel: "Charity Commission", taxRate: 25, currency: "GBP",
    mission: "Cancer Research UK funds more than half of all publicly funded cancer research in the UK. Their scientists have been behind breakthroughs including tamoxifen for breast cancer, PET scanning, and immunotherapy.\n\nSurvival rates have doubled in the last 40 years, largely thanks to CRUK-funded research. Their goal: 3 in 4 people surviving cancer by 2034.",
    impact: J(["Funds 4,000+ scientists and clinicians across the UK","£735 million income dedicated to research","Survival rates doubled from 25% to 50% in 40 years","Pioneer of 7 cancer drugs now in clinical use","World's largest charity funder of cancer clinical trials"]),
    crisisEligible: false,
    foundingStory: "Cancer Research UK was formed in 2002 by the merger of the Cancer Research Campaign (1923) and the Imperial Cancer Research Fund (1902), combining a century of British cancer research into one organisation. Their founding principle: scientific excellence, funded by public generosity.",
    howMoneyHelps: J([{amount:5,description:"Funds 15 minutes of cancer research"},{amount:25,description:"Funds a PhD student's work for a day"},{amount:100,description:"Supports a clinical trial participant"}]),
    milestones: J([{year:1902,title:"ICRF Founded",description:"One of CRUK's predecessor charities established"},{year:2002,title:"CRUK Created",description:"Merger forms world's largest independent cancer charity"},{year:2018,title:"Immunotherapy Breakthroughs",description:"CRUK-funded research leads to new cancer treatments"},{year:2024,title:"£735M Research",description:"Record research investment"}]),
    financialBreakdown: J({programs:83,admin:8,fundraising:9}), fundraisingEfficiency: "83 pence of every pound funds cancer research",
    countryOfOrigin: "GB", foundedYear: 2002, websiteUrl: "https://www.cancerresearchuk.org",
    certifications: J([{name:"Charity Commission",year:2002}]),
    jurisdictionsEligible: J(["GB"]), loiColucheEligible: false, crossBorderMethod: "none",
  },
  {
    id: nanoid(), name: "Macmillan Cancer Support", description: "Not research, but people: financial, emotional, and practical support for everyone affected by cancer.",
    category: "health", icon: "💚", qualityLabel: "Charity Commission", taxRate: 25, currency: "GBP",
    mission: "While others research the cure, Macmillan supports the person. Founded in 1911, Macmillan provides specialist nurses, financial guidance, and emotional support for cancer patients and their families.\n\n10,881 Macmillan professionals work across the NHS, funded entirely by donations. Their mission: no one should face cancer alone.",
    impact: J(["10,881 Macmillan nurses and professionals across the UK","Provided financial support to 385,000 people","Macmillan Support Line handled 400,000 calls","Generated £1.2 billion of income tax and benefits for cancer patients","97% of callers would recommend the support line"]),
    crisisEligible: false,
    foundingStory: "In 1911, Douglas Macmillan watched his father die of cancer without proper pain management or support. He founded the Society for the Prevention and Relief of Cancer to ensure no one would face the disease without help. Over a century later, his promise endures.",
    howMoneyHelps: J([{amount:10,description:"30 minutes with a Macmillan specialist nurse"},{amount:25,description:"A financial guidance session for a cancer patient"},{amount:50,description:"A day of end-of-life care support"}]),
    milestones: J([{year:1911,title:"Founded",description:"Douglas Macmillan's promise after his father's death"},{year:1975,title:"First Macmillan Nurse",description:"Specialist cancer nursing programme begins"},{year:2012,title:"World's Biggest Coffee Morning",description:"Raises £20M in a single day"},{year:2024,title:"10,881 Professionals",description:"Largest ever workforce supporting cancer patients"}]),
    financialBreakdown: J({programs:79,admin:10,fundraising:11}), fundraisingEfficiency: "79 pence of every pound provides direct cancer support",
    countryOfOrigin: "GB", foundedYear: 1911, websiteUrl: "https://www.macmillan.org.uk",
    certifications: J([{name:"Charity Commission",year:1911}]),
    jurisdictionsEligible: J(["GB"]), loiColucheEligible: false, crossBorderMethod: "none",
  },
  {
    id: nanoid(), name: "British Heart Foundation", description: "The UK's largest funder of cardiovascular research: £100M+ per year to end heartbreak from heart disease.",
    category: "health", icon: "❤️‍🩹", qualityLabel: "Charity Commission", taxRate: 25, currency: "GBP",
    mission: "Founded in 1961 by a group of medical professionals concerned that heart disease was the UK's biggest killer with almost no research funding. BHF has since invested over £2 billion in cardiovascular research.\n\nBHF-funded research led to the development of cholesterol-lowering statins, defibrillators in public places, and pioneering heart surgery techniques.",
    impact: J(["Invested £100M+ in cardiovascular research in 2024","Funded 2,600 researchers across UK universities","30,000+ defibrillators placed in public locations","Heart and circulatory disease death rates halved since 1960s","80,000 CPR training sessions delivered"]),
    crisisEligible: false,
    foundingStory: "In 1961, a group of physicians realised that coronary heart disease was killing more people than any other condition, yet almost no money was being spent to understand or prevent it. They created the British Heart Foundation to fund the science that could save millions of lives.",
    howMoneyHelps: J([{amount:5,description:"Funds 15 minutes of heart research"},{amount:20,description:"A defibrillator training session"},{amount:100,description:"Funds a full day of cardiovascular research"}]),
    milestones: J([{year:1961,title:"BHF Founded",description:"Doctors unite to fight the UK's biggest killer"},{year:1980,title:"Statin Research",description:"BHF-funded work leads to cholesterol-lowering statins"},{year:2000,title:"Public Defibrillators",description:"Campaign places defibrillators in public spaces"},{year:2024,title:"£100M+ Research",description:"Record annual research investment"}]),
    financialBreakdown: J({programs:78,admin:10,fundraising:12}), fundraisingEfficiency: "78 pence of every pound funds heart research and prevention",
    countryOfOrigin: "GB", foundedYear: 1961, websiteUrl: "https://www.bhf.org.uk",
    certifications: J([{name:"Charity Commission",year:1961}]),
    jurisdictionsEligible: J(["GB"]), loiColucheEligible: false, crossBorderMethod: "none",
  },
  // US (2)
  {
    id: nanoid(), name: "St. Jude Children's Research Hospital", description: "No child is denied treatment: families never receive a bill. The most trusted nonprofit in America.",
    category: "children", icon: "🌟", qualityLabel: "Charity Navigator 4-star", taxRate: 37, currency: "USD",
    mission: "Founded in 1962 by entertainer Danny Thomas, St. Jude treats the toughest childhood cancers and shares discoveries freely so every child can be saved, not just those at St. Jude.\n\nFamilies never receive a bill for treatment, travel, housing, or food. Because all a family should worry about is helping their child live. Since opening, the survival rate for childhood cancer has risen from 20% to over 80%.",
    impact: J(["Childhood cancer survival rate risen from 20% to 80%+","Treated children from all 50 US states and around the world","Shared discoveries with doctors in 88 countries","$1B+ annual operating budget, 100% from donations","Most trusted nonprofit in America (Chronicle of Philanthropy)"]),
    crisisEligible: false,
    foundingStory: "In the 1950s, struggling entertainer Danny Thomas prayed to St. Jude Thaddeus, patron saint of lost causes: 'Help me find my way in life, and I will build you a shrine.' When success came, Thomas kept his promise. In 1962, he opened St. Jude Children's Research Hospital in Memphis, dedicated to children who no other hospital would take.",
    howMoneyHelps: J([{amount:10,description:"A day of housing for a patient family near the hospital"},{amount:50,description:"Lab supplies for childhood cancer research"},{amount:100,description:"A day of treatment for a child (families never billed)"}]),
    milestones: J([{year:1962,title:"St. Jude Opens",description:"Danny Thomas fulfils his promise"},{year:1983,title:"First Bone Marrow Transplant",description:"Pioneering treatment for childhood leukaemia"},{year:2018,title:"$1B Budget",description:"Largest paediatric research budget globally"},{year:2024,title:"80%+ Survival",description:"Childhood cancer survival transformed"}]),
    financialBreakdown: J({programs:82,admin:8,fundraising:10}), fundraisingEfficiency: "82 cents of every dollar treats children and funds research",
    countryOfOrigin: "US", foundedYear: 1962, websiteUrl: "https://www.stjude.org",
    certifications: J([{name:"Charity Navigator 4-star",year:2020}]),
    jurisdictionsEligible: J([]), loiColucheEligible: false, crossBorderMethod: "none",
  },
  {
    id: nanoid(), name: "Direct Relief", description: "100% of donor cash goes to programs. Endowment covers overhead. Equipping health workers in 100+ countries.",
    category: "humanitarian", icon: "💊", qualityLabel: "Charity Navigator 4-star", taxRate: 37, currency: "USD",
    mission: "Direct Relief provides medical supplies to health workers in resource-poor areas and disaster zones. What makes them unique: 100% of cash donations go directly to programs because an endowment covers all overhead.\n\nIn 2024, Direct Relief provided $2.1 billion worth of medical supplies to 100+ countries, making it one of the largest humanitarian organisations by value delivered.",
    impact: J(["$2.1 billion in medical supplies delivered in 2024","Equipped 10,500 health facilities in 100+ countries","Responded to 50+ natural disasters and emergencies","100% of cash donations go to programs","Forbes #5 most efficient large charity"]),
    crisisEligible: true,
    foundingStory: "In 1948, Estonian immigrant William Zimdin began collecting surplus medicines from US companies and shipping them to war-ravaged Europe. He called his effort Direct Relief. Seventy-five years later, the organisation delivers billions of dollars in medical aid, funded by an endowment model that means every donated dollar goes to the field.",
    howMoneyHelps: J([{amount:1,description:"Provides 3 defined daily doses of essential medicine"},{amount:25,description:"A medical supply kit for a rural clinic"},{amount:100,description:"Equips a health facility for a full day"}]),
    milestones: J([{year:1948,title:"Founded",description:"William Zimdin ships medicine to post-war Europe"},{year:2005,title:"Tsunami Response",description:"Major disaster response capabilities established"},{year:2020,title:"COVID Response",description:"$1.7B in PPE and medical supplies distributed"},{year:2024,title:"$2.1B Delivered",description:"Record year of medical supply distribution"}]),
    financialBreakdown: J({programs:100,admin:0,fundraising:0}), fundraisingEfficiency: "100 cents of every dollar goes directly to medical programs (endowment covers overhead)",
    countryOfOrigin: "US", foundedYear: 1948, websiteUrl: "https://www.directrelief.org",
    certifications: J([{name:"Charity Navigator 4-star",year:2018}]),
    jurisdictionsEligible: J([]), loiColucheEligible: false, crossBorderMethod: "none",
  },
  // French (4)
  {
    id: nanoid(), name: "Action contre la Faim", description: "Fighting hunger worldwide: nutrition, food security, water, and sanitation in 50+ countries.",
    category: "hunger", icon: "🍽️", qualityLabel: "Don en Confiance", taxRate: 75, currency: "EUR",
    mission: "Founded in 1979 by French intellectuals including Nobel laureate Bernard Kouchner, Action contre la Faim (Action Against Hunger) fights hunger in over 50 countries.\n\nThe organisation treats acute malnutrition in children, builds sustainable food systems, provides clean water, and responds to food crises caused by conflict and climate change.",
    impact: J(["Treated 5.5 million children for acute malnutrition in 2024","Provided clean water to 12 million people","Active in 51 countries with 8,900 staff","Trained 340,000 community health workers","Emergency food response in 20+ crises"]),
    crisisEligible: true,
    foundingStory: "In 1979, a group of French intellectuals, physicians, and writers witnessed the famine caused by the Afghan and Cambodian conflicts. Among them was Bernard Kouchner (co-founder of MSF). They created Action contre la Faim to address hunger as both an emergency and a structural injustice.",
    howMoneyHelps: J([{amount:1,description:"10 sachets of therapeutic ready-to-use food"},{amount:10,description:"Treats one child for malnutrition for a week"},{amount:50,description:"Clean water for 50 people for a month"}]),
    milestones: J([{year:1979,title:"Founded in Paris",description:"French intellectuals respond to hunger crises"},{year:1998,title:"Global Expansion",description:"Establishes offices in US, UK, and Spain"},{year:2015,title:"SDG Commitment",description:"Key partner in Zero Hunger Goal"},{year:2024,title:"5.5M Children Treated",description:"Largest ever malnutrition treatment programme"}]),
    financialBreakdown: J({programs:87,admin:7,fundraising:6}), fundraisingEfficiency: "87 cents of every euro fights hunger directly",
    countryOfOrigin: "FR", foundedYear: 1979, websiteUrl: "https://www.actioncontrelafaim.org",
    certifications: J([{name:"Don en Confiance",year:1989}]),
    jurisdictionsEligible: J(["FR","GB","ES"]), loiColucheEligible: true, crossBorderMethod: "national_entity",
  },
  {
    id: nanoid(), name: "Médecins du Monde", description: "Healthcare for excluded populations: the homeless, undocumented migrants, sex workers, and drug users.",
    category: "humanitarian", icon: "🩺", qualityLabel: "Don en Confiance", taxRate: 75, currency: "EUR",
    mission: "Founded in 1980 by Bernard Kouchner (who also co-founded MSF), Médecins du Monde focuses specifically on people excluded from healthcare: the homeless, undocumented migrants, sex workers, and people who use drugs.\n\nIn France, MdM runs free clinics in major cities. Internationally, they provide healthcare in crisis zones and advocate for universal health coverage.",
    impact: J(["Operated 120 free medical centres in France","Provided 300,000 medical consultations to excluded populations","Active in 45 countries","Advocated for universal healthcare access in EU policy","12,000 volunteers across France"]),
    crisisEligible: true,
    foundingStory: "In 1980, Bernard Kouchner left MSF over a disagreement about neutrality vs advocacy. He founded Médecins du Monde with a clear position: doctors should not only treat but also speak out about the injustices that cause illness. MdM would focus on the most invisible patients, those society has turned away.",
    howMoneyHelps: J([{amount:5,description:"A medical consultation for a homeless person"},{amount:20,description:"A complete vaccination kit"},{amount:100,description:"Runs a mobile clinic for one day"}]),
    milestones: J([{year:1980,title:"Founded by Kouchner",description:"Focuses on excluded populations"},{year:1999,title:"French Free Clinics",description:"Opens permanent medical centres in Paris, Lyon, Marseille"},{year:2015,title:"Refugee Health",description:"Major programme for refugee healthcare in Europe"},{year:2024,title:"300K Consultations",description:"Record year of healthcare for the excluded"}]),
    financialBreakdown: J({programs:84,admin:8,fundraising:8}), fundraisingEfficiency: "84 cents of every euro provides healthcare to those excluded from the system",
    countryOfOrigin: "FR", foundedYear: 1980, websiteUrl: "https://www.medecinsdumonde.org",
    certifications: J([{name:"Don en Confiance",year:2002}]),
    jurisdictionsEligible: J(["FR"]), loiColucheEligible: true, crossBorderMethod: "none",
  },
  {
    id: nanoid(), name: "Fondation pour la Recherche Médicale", description: "France's leading independent funder of medical research: from Alzheimer's to rare diseases, gene therapy to vaccines.",
    category: "health", icon: "🧬", qualityLabel: "Don en Confiance", taxRate: 66, currency: "EUR",
    mission: "The Fondation pour la Recherche Médicale (FRM) has funded medical breakthroughs for over 75 years. Unlike disease-specific charities, FRM supports research across all pathologies: cancer, Alzheimer's, rare diseases, infectious disease, gene therapy.\n\nFRM is independently governed, with zero government or industry funding. This independence lets them fund high-risk, high-reward research that others won't touch.",
    impact: J(["Funded 720 research projects in 2024","€60 million invested in medical research annually","Supports 400+ researchers at any given time","Contributed to development of mRNA vaccine technology","75+ years of unbroken research funding"]),
    crisisEligible: false,
    foundingStory: "In 1947, a group of physicians and scientists at the Sorbonne saw that French medical research was critically underfunded after the war. They created the FRM to fund science based purely on merit, free from government priorities or industry interests. For over 75 years, that independence has been their greatest asset.",
    howMoneyHelps: J([{amount:10,description:"Funds 2 hours of medical research"},{amount:50,description:"Supports a researcher's grant for a day"},{amount:200,description:"Funds a PhD research month"}]),
    milestones: J([{year:1947,title:"FRM Founded",description:"Sorbonne physicians create independent research fund"},{year:1982,title:"AIDS Research",description:"Early funder of HIV/AIDS research in France"},{year:2015,title:"Gene Therapy",description:"Funds breakthrough gene therapy trials"},{year:2024,title:"720 Projects",description:"Largest ever annual research portfolio"}]),
    financialBreakdown: J({programs:80,admin:11,fundraising:9}), fundraisingEfficiency: "80 cents of every euro funds medical research",
    countryOfOrigin: "FR", foundedYear: 1947, websiteUrl: "https://www.frm.org",
    certifications: J([{name:"Don en Confiance",year:1998}]),
    jurisdictionsEligible: J(["FR"]), loiColucheEligible: false, crossBorderMethod: "none",
  },
  {
    id: nanoid(), name: "Croix-Rouge française", description: "France's largest humanitarian charity: 97,000 volunteers, first aid, emergency response, social inclusion, and international aid.",
    category: "humanitarian", icon: "⛑️", qualityLabel: "Don en Confiance", taxRate: 75, currency: "EUR",
    mission: "The French Red Cross, founded in 1864 (one year after the ICRC), is one of the oldest and largest national Red Cross societies. With 97,000 volunteers and 18,000 employees, it is France's premier emergency response and social action organisation.\n\nBeyond emergencies, the French Red Cross runs shelters, food banks, training programmes, and elderly care facilities. It is a pillar of French civil society.",
    impact: J(["97,000 volunteers active across metropolitan and overseas France","First responder to every major disaster in France","Operates 600+ social action facilities","Trains 1 million people in first aid annually","International aid in 30+ countries"]),
    crisisEligible: true,
    foundingStory: "In 1864, one year after the founding of the ICRC in Geneva, the Société française de secours aux blessés militaires was created. It would become the Croix-Rouge française, embedding Henry Dunant's vision of humanitarian care into French national life. For 160 years, the French Red Cross has been wherever people need help.",
    howMoneyHelps: J([{amount:2,description:"Provides an emergency meal for a person in crisis"},{amount:15,description:"A complete first aid kit"},{amount:50,description:"Emergency shelter for a displaced person for one night"}]),
    milestones: J([{year:1864,title:"Founded",description:"One year after the ICRC, France creates its Red Cross"},{year:1940,title:"WWII Response",description:"Cares for prisoners, refugees, and wounded throughout the war"},{year:2003,title:"Heatwave Response",description:"Major intervention during France's deadly heatwave"},{year:2024,title:"97K Volunteers",description:"France's largest volunteer humanitarian workforce"}]),
    financialBreakdown: J({programs:85,admin:9,fundraising:6}), fundraisingEfficiency: "85 cents of every euro funds emergency response and social action",
    countryOfOrigin: "FR", foundedYear: 1864, websiteUrl: "https://www.croix-rouge.fr",
    certifications: J([{name:"Don en Confiance",year:2024}]),
    jurisdictionsEligible: J(["FR"]), loiColucheEligible: true, crossBorderMethod: "none",
  },
];

db.insert(schema.charities).values(charityData).run();

// Seed jurisdiction tax rules for all 5 countries
const taxRules = [
  { countryCode: "FR", standardRate: 66, enhancedRate: 75, enhancedCeiling: 2000, incomeCapPct: 20, receiptFormat: "cerfa_11580" },
  { countryCode: "GB", standardRate: 25, enhancedRate: 40, enhancedCeiling: 0, incomeCapPct: 100, receiptFormat: "gift_aid_receipt" },
  { countryCode: "DE", standardRate: 42, enhancedRate: 42, enhancedCeiling: 0, incomeCapPct: 20, receiptFormat: "zuwendungsbestaetigung" },
  { countryCode: "BE", standardRate: 45, enhancedRate: 45, enhancedCeiling: 397850, incomeCapPct: 10, receiptFormat: "attestation_281_71" },
  { countryCode: "ES", standardRate: 40, enhancedRate: 80, enhancedCeiling: 250, incomeCapPct: 10, receiptFormat: "certificado_donacion" },
];
for (const rule of taxRules) {
  db.insert(schema.jurisdictionTaxRules).values({ id: nanoid(), ...rule }).run();
}

console.log("✅ Database seeded successfully");
console.log(`  ${charityData.length} charities with full content`);
console.log("  5 jurisdictions (FR, GB, DE, BE, ES)");

sqlite.close();
