"use client";

import { useState } from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10, color: "#1a1a2e" },
  header: { marginBottom: 24 },
  title: { fontSize: 22, fontWeight: "bold", color: "#0f1f38", marginBottom: 4 },
  subtitle: { fontSize: 12, color: "#7a9cc6" },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 13, fontWeight: "bold", marginBottom: 8, color: "#0f1f38", borderBottom: "1 solid #e0e0e0", paddingBottom: 4 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 },
  label: { color: "#555" },
  value: { fontWeight: "bold" },
  bigNumber: { fontSize: 28, fontWeight: "bold", color: "#4a9eff", marginVertical: 8 },
  greenNumber: { fontSize: 28, fontWeight: "bold", color: "#2d8a6e", marginVertical: 8 },
  tableHeader: { flexDirection: "row", borderBottom: "1 solid #ccc", paddingBottom: 4, marginBottom: 4, fontWeight: "bold" },
  tableRow: { flexDirection: "row", paddingVertical: 2 },
  col1: { width: "40%" },
  col2: { width: "20%", textAlign: "right" },
  col3: { width: "20%", textAlign: "right" },
  col4: { width: "20%", textAlign: "right" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, borderTop: "1 solid #e0e0e0", paddingTop: 8, fontSize: 8, color: "#999", flexDirection: "row", justifyContent: "space-between" },
});

interface PdfData {
  userName: string;
  userEmail: string;
  year: number;
  totalDonated: number;
  totalTaxCredit: number;
  charityBreakdown: { name: string; percentage: number; donated: number; taxRate: number; taxCredit: number }[];
  monthlyBreakdown: { month: string; amount: number }[];
  rate75: { total: number; ceiling: number; taxCredit: number };
  rate66: { total: number; taxCredit: number };
}

function SummaryPdf({ data }: { data: PdfData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>RoundUp Year End Summary</Text>
          <Text style={styles.subtitle}>{data.userName} | {data.year}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Total Donations</Text>
          <Text style={styles.greenNumber}>EUR {data.totalDonated.toFixed(2)}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Donations by Charity</Text>
          <View style={styles.tableHeader}>
            <Text style={styles.col1}>Charity</Text>
            <Text style={styles.col2}>Allocation</Text>
            <Text style={styles.col3}>Tax Rate</Text>
            <Text style={styles.col4}>Amount</Text>
          </View>
          {data.charityBreakdown.map((c, i) => (
            <View key={i} style={styles.tableRow}>
              <Text style={styles.col1}>{c.name}</Text>
              <Text style={styles.col2}>{c.percentage}%</Text>
              <Text style={styles.col3}>{c.taxRate}%</Text>
              <Text style={styles.col4}>EUR {c.donated.toFixed(2)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Monthly Breakdown</Text>
          {data.monthlyBreakdown.map((m, i) => (
            <View key={i} style={styles.row}>
              <Text style={styles.label}>{m.month}</Text>
              <Text style={styles.value}>EUR {m.amount.toFixed(2)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.footer}>
          <Text>Generated by RoundUp</Text>
          <Text>{new Date().toLocaleDateString("en-GB")}</Text>
        </View>
      </Page>
    </Document>
  );
}

function TaxCalcPdf({ data }: { data: PdfData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Tax Calculation Report</Text>
          <Text style={styles.subtitle}>{data.userName} | {data.year}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Estimated Tax Credit</Text>
          <Text style={styles.bigNumber}>EUR {data.totalTaxCredit.toFixed(2)}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>75% Rate (Loi Coluche)</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Total donated at 75%</Text>
            <Text style={styles.value}>EUR {data.rate75.total.toFixed(2)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Annual ceiling</Text>
            <Text style={styles.value}>EUR {data.rate75.ceiling.toFixed(2)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Eligible amount</Text>
            <Text style={styles.value}>EUR {Math.min(data.rate75.total, data.rate75.ceiling).toFixed(2)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Tax credit (75%)</Text>
            <Text style={styles.value}>EUR {data.rate75.taxCredit.toFixed(2)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>66% Rate (Standard)</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Total donated at 66%</Text>
            <Text style={styles.value}>EUR {data.rate66.total.toFixed(2)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Tax credit (66%)</Text>
            <Text style={styles.value}>EUR {data.rate66.taxCredit.toFixed(2)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Breakdown by Charity</Text>
          <View style={styles.tableHeader}>
            <Text style={styles.col1}>Charity</Text>
            <Text style={styles.col2}>Donated</Text>
            <Text style={styles.col3}>Rate</Text>
            <Text style={styles.col4}>Credit</Text>
          </View>
          {data.charityBreakdown.map((c, i) => (
            <View key={i} style={styles.tableRow}>
              <Text style={styles.col1}>{c.name}</Text>
              <Text style={styles.col2}>EUR {c.donated.toFixed(2)}</Text>
              <Text style={styles.col3}>{c.taxRate}%</Text>
              <Text style={styles.col4}>EUR {c.taxCredit.toFixed(2)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.footer}>
          <Text>Generated by RoundUp</Text>
          <Text>{new Date().toLocaleDateString("en-GB")}</Text>
        </View>
      </Page>
    </Document>
  );
}

export function usePdfDownload() {
  const [loading, setLoading] = useState<string | null>(null);

  async function downloadPdf(type: "summary" | "tax") {
    setLoading(type);
    try {
      const res = await fetch(`/api/tax/pdf?type=${type}`);
      const data: PdfData = await res.json();

      const doc = type === "summary" ? <SummaryPdf data={data} /> : <TaxCalcPdf data={data} />;
      const blob = await pdf(doc).toBlob();

      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `roundup_${type}_${data.year}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("PDF generation failed:", err);
    }
    setLoading(null);
  }

  return { downloadPdf, loading };
}
